layout_spectrum: 0.1264629
color:
  saturation: 0.8260441
  lightness: 0.676189
  brandStrength: 0.9135338
  brandColors:
    - '#0B060A'
    - '#EAEDD0'
    - '#FB3067'
    - '#A08E76'
    - '#66453E'
  rhythmicContrast: 0.536421
typography_spectrum: 0.4387755
name: Jack
